### ISSUE TITLE
SelectiveFastClick is not defined

### ISSUE THREAD

**Issue by gamegoofs2** [matthew-andrews/selective-fastclick#2]
When trying to use SelectiveFastClick is get the js error of "Uncaught ReferenceError: SelectiveFastClick is not defined". I notice it is happening even on your example. I am using the packaged version. My code looks like this:

SelectiveFastClick.attach(document.body, '.dialogO');

Do you have a solution for this?

**Comment by matthew-andrews** [comment]
By which method are you including SelectiveFastClick? Did you download it from wzrd.in?

**Comment by gamegoofs2** [comment]
Yeah I think. The link in the README that says "download the prebuild package" http://wzrd.in/standalone/selective-fastclick@latest

**Comment by matthew-andrews** [comment]
Yeah - it looks like the way wzrd.in means it gets exposed on `window.selectiveFastclick` :-/.  I'll add a note...

**Comment by gamegoofs2** [comment]
So if I say window.selectiveFastclick that should work?

**Comment by matthew-andrews** [comment]
I believe so.  Would you mind checking and letting me know?

**Comment by gamegoofs2** [comment]
window.selectiveFastclick is correct. I submitted a pull request, but I think you already updated.

**Comment by matthew-andrews** [comment]
Thanks for your help :-).
